apiVersion: v1
kind: Pod
metadata:
  name: nginx-unprivileged4
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    supplementalGroups:
      - 1000
  containers:
    - name: nginx-unprivileged
      image: nginxinc/nginx-unprivileged:latest
      ports:
        - containerPort: 8080
      securityContext:
        privileged: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
      
