# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: computejob
#   namespace: echo-nils-production
# spec:
#   template:
#     metadata:
#       namespace: echo-nils-production
#       labels:
#         app: computejobtest
#     spec:
#       restartPolicy: Never
#       containers:
#         - name: nginx-unprivileged5
#           image: nilsgustavstrabo/compute:latest
#           ports:
#             - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: computejob
#   namespace: echo-nils-production
# spec:
#   selector:
#     app: computejobtest
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: test
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: test-app
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false