apiVersion: v1
kind: Pod
metadata:
  name: nginx-unprivileged5
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
    supplementalGroups:
      - 1001
  containers:
    - name: nginx-unprivileged5
      image: nilsgustavstrabo/compute:latest
      #image: nginx:latest
      ports:
        - containerPort: 80
      securityContext:
        privileged: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
      volumeMounts:
        - name: radix-sp-acr-azure
          mountPath: /compute/.azure
          readOnly: true
  volumes:
    - name: radix-sp-acr-azure
      secret:
        secretName: radix-sp-acr-azure    
