---
apiVersion: batch/v1
kind: Job
metadata:
  name: computejob
  namespace: echo-nils-production
spec:
  template:
    metadata:
      namespace: echo-nils-production
      labels:
        app: computejobtest
    spec:
      restartPolicy: Never
      containers:
        - name: nginx-unprivileged5
          image: nilsgustavstrabo/compute:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: computejob
  namespace: echo-nils-production
spec:
  selector:
    app: computejobtest
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080