apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: echo-nils
spec:
  environments:
    - name: dev
      build:
        from: config
    - name: production
  jobs:
    - name: compute
      src: ./compute
      dockerfileName: Dockerfile
      ports:
       - name: http
         port: 3001
      schedulerPort: 8888
      payload:
        path: /path/to/payload2
      variables:
        COMPUTE_SOURCE: somewhere
      secrets:
        - COMPUTESECRET
        - COMPUTESECRET2
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
          volumeMounts:
            - type: blob
              name: volume-name
              container: container-dev
              path: /path/in/container/to/mount/to
        - environment: production
          variables:
            PORT: 3001
            NODE_ENV: "production"
            PROD_VAR: "only_in_prod"
          volumeMounts:
            - type: blob
              name: volume-name
              container: container-prod
              path: /path/in/container/to/mount/to
  components:
    - name: echo
      src: ./echo
      ports:
      - name: http
        port: 3001
      secrets:
        - SECRET1
        - SECRET2
      variables:
        VAR1: var1
        VAR2: var2
      environmentConfig:
        - environment: dev
          runAsNonRoot: true
          variables:
            PORT: 3001
            NODE_ENV: "dev"
          monitoring: false
          replicas: 1
          resources:
            requests:
              memory: "55Mi"
              cpu: "22m"
            limits:
              memory: "66Mi"
              cpu: "33m"
        - environment: production
          monitoring: true
          runAsNonRoot: true
          variables:
            PORT: 3001
          resources:
            requests:
              memory: "155Mi"
              cpu: "122m"
            limits:
              memory: "166Mi"
              cpu: "133m"
    - name: www
      src: ./www
      ports:
       - name: http
         port: 3002
      publicPort: http
      variables:
        ECHO_URL: "http://echo:3001"
      secrets:
        - WWWSECRET
      environmentConfig:
        - environment: dev
          runAsNonRoot: true
          variables:
            PORT: 3002
            NODE_ENV: "dev"
          monitoring: true
          resources:
            requests:
              memory: "150Mi"
              cpu: "10m"
            limits:
              memory: "150Mi"
              cpu: "20m"
          replicas: 1
        - environment: production
          runAsNonRoot: true  
          monitoring: false
          variables:
            PORT: 3002
    - name: nginx
      image: bitnami/redis:latest
      alwaysPullImageOnDeploy: true
      ports:
        - name: redis
          port: 6379
      variables:
        ALLOW_EMPTY_PASSWORD: "yes"          
