apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: echo-nils
spec:
  dnsAppAlias:
    environment: production
    component: www
  privateImageHubs:
    privaterepodeleteme.azurecr.io:
      username: 23452345-3d71-44a7-8476-50e8b281abbc
      email: radix@statoilsrm.onmicrosoft.com
    privaterepodeleteme2.azurecr.io:
      username: 23423424-3d71-44a7-8476-50e8b281abb2
      email: radix@statoilsrm.onmicrosoft.com
  environments:
    - name: dev
      build:
        from: config
    - name: production
  jobs:
    - name: compute
      src: ./compute
      dockerfileName: Dockerfile
      ports:
       - name: http
         port: 3001
      schedulerPort: 8889
      payload:
        path: /path/to/payload2
      variables:
        COMPUTE_SOURCE: somewhere
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
          monitoring: true
          resources:
            requests:
              memory: "200Mi"
              cpu: "20m"
            limits:
              memory: "750Mi"
              cpu: "50m"
          # volumeMounts:
          #   - type: blob
          #     name: computedata
          #     container: dev_compute_container
          #     path: /dev_compute
        - environment: production
          variables:
            PORT: 3002
            NODE_ENV: "production"
            PROD_VAR: "only_in_prod"
          monitoring: false
          resources:
            requests:
              memory: "200Mi"
              cpu: "20m"
            limits:
              memory: "750Mi"
              cpu: "50m"
          # volumeMounts:
          #   - type: blob
          #     name: computedata
          #     container: prod_compute_container
          #     path: /prod_compute
    # - name: compute2
    #   src: ./compute
    #   schedulerPort: 8889
    #   ports:
    #    - name: http
    #      port: 3001
    #   variables:
    #     COMPUTE_SOURCE: somewhere_else
  # cronjobs:
  #   - name: etl
  #     src: ./etl
      # schedule: * 0 0 0 0
      # ports:
      #   - name: http
      #     port: 3000
      # environmentConfig:
      #   - environment: dev
      #     schedule: * */2 0 0 0
      # secrets:
      #   - SECRET1
      #   - SECRET2
  components:
    - name: echo
      src: ./echo
      ports:
      - name: http
        port: 3001
      secrets:
        - SECRET1
        - SECRET2
      variables:
        VAR1: var1
        VAR2: var2
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
          monitoring: false
          # volumeMounts:
          #   - type: blob
          #     name: blobvol
          #     container: devcontainer
          #     path: /devdir
          replicas: 1
          resources:
            requests:
              memory: "55Mi"
              cpu: "22m"
            limits:
              memory: "66Mi"
              cpu: "33m"
        - environment: production
          monitoring: true
          variables:
            PORT: 3001
          # volumeMounts:
          #   - type: blob
          #     name: blobvol
          #     container: prodcontainer
          #     path: /proddir
          resources:
            requests:
              memory: "155Mi"
              cpu: "122m"
            limits:
              memory: "166Mi"
              cpu: "133m"
    - name: www
      src: ./www
      ports:
       - name: http
         port: 3001
      publicPort: http
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
            ECHO_URL: "http://echo:3001"
          monitoring: true
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 1
        - environment: production
          monitoring: false
          variables:
            PORT: 3001
            ECHO_URL: "http://echo:3001"
