apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: echo-nils
spec:
  environments:
    - name: dev
      build:
        from: config
    - name: production
  jobs:
    - name: compute
      src: ./compute
      dockerfileName: Dockerfile
      ports:
       - name: http
         port: 3001
      schedulerPort: 8889
      payload:
        path: /path/to/payload2
      variables:
        COMPUTE_SOURCE: somewhere
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
          monitoring: true
          resources:
            requests:
              memory: "200Mi"
              cpu: "20m"
            limits:
              memory: "750Mi"
              cpu: "50m"
          # volumeMounts:
          #   - type: blob
          #     name: computedata
          #     container: dev_compute_container
          #     path: /dev_compute
        - environment: production
          variables:
            PORT: 3002
            NODE_ENV: "production"
            PROD_VAR: "only_in_prod"
          monitoring: false
          resources:
            requests:
              memory: "200Mi"
              cpu: "20m"
            limits:
              memory: "750Mi"
              cpu: "50m"
          # volumeMounts:
          #   - type: blob
          #     name: computedata
          #     container: prod_compute_container
          #     path: /prod_compute
    # - name: compute2
    #   src: ./compute
    #   schedulerPort: 8889
    #   ports:
    #    - name: http
    #      port: 3001
    #   variables:
    #     COMPUTE_SOURCE: somewhere_else
  components:
    - name: echo
      src: ./echo
      ports:
      - name: http
        port: 3001
      secrets:
        - SECRET1
        - SECRET2
      variables:
        VAR1: var1
        VAR2: var2
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
          monitoring: false
          replicas: 1
          resources:
            requests:
              memory: "55Mi"
              cpu: "22m"
            limits:
              memory: "66Mi"
              cpu: "33m"
        - environment: production
          monitoring: true
          variables:
            PORT: 3001
          resources:
            requests:
              memory: "155Mi"
              cpu: "122m"
            limits:
              memory: "166Mi"
              cpu: "133m"
    - name: www
      src: ./www
      ports:
       - name: http
         port: 3002
      publicPort: http
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3002
            NODE_ENV: "dev"
            ECHO_URL: "http://echo:3001"
          monitoring: true
          resources:
            requests:
              memory: "150Mi"
              cpu: "10m"
            limits:
              memory: "150Mi"
              cpu: "20m"
          replicas: 1
        - environment: production
          monitoring: false
          variables:
            PORT: 3002
            ECHO_URL: "http://echo:3001"
