apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: echo-nils
spec:
  environments:
    - name: dev
      build:
        from: config
    - name: production
  jobs:
    - name: compute
      src: ./compute
      dockerfileName: Dockerfile
      ports:
       - name: http
         port: 3001
      schedulerPort: 8889
      payload:
        path: /path/to/payload
      variables:
        COMPUTE_SOURCE: somewhere
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
          monitoring: true
          resources:
            requests:
              memory: "50Mi"
              cpu: "20m"
            limits:
              memory: "60Mi"
              cpu: "30m"
          volumeMounts:
            - type: blob
              name: computedata
              container: dev_compute_container
              path: /dev_compute
        - environment: production
          variables:
            PORT: 3002
            NODE_ENV: "production"
            PROD_VAR: "only_in_prod"
          monitoring: false
          resources:
            requests:
              memory: "150Mi"
              cpu: "120m"
            limits:
              memory: "160Mi"
              cpu: "130m"
          volumeMounts:
            - type: blob
              name: computedata
              container: prod_compute_container
              path: /prod_compute
    - name: compute2
      src: ./compute
      ports:
       - name: http
         port: 3001
      variables:
        COMPUTE_SOURCE: somewhere_else
  # cronjobs:
  #   - name: etl
  #     src: ./etl
      # schedule: * 0 0 0 0
      # ports:
      #   - name: http
      #     port: 3000
      # environmentConfig:
      #   - environment: dev
      #     schedule: * */2 0 0 0
      # secrets:
      #   - SECRET1
      #   - SECRET2
  components:
    - name: echo
      src: ./echo
      ports:
      - name: http
        port: 3001
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
          monitoring: false
          volumeMounts:
            - type: blob
              name: blobvol
              container: devcontainer
              path: /devdir
          replicas: 1
        - environment: production
          monitoring: true
          volumeMounts:
            - type: blob
              name: blobvol
              container: prodcontainer
              path: /proddir
    # - name: echo2
    #   src: ./echo
    #   ports:
    #   - name: http
    #     port: 3001
    #   public: false
    #   environmentConfig:
    #     - environment: dev
    #       variables:
    #         PORT: 3001
    #         NODE_ENV: "dev"
    #       monitoring: true
    #       # resources:
    #       #   requests:
    #       #     memory: "42Mi"
    #       #     cpu: "10m"
    #       #   limits:
    #       #     memory: "50Mi"
    #       #     cpu: "20m"
    #       replicas: 1
    - name: www
      src: ./www
      ports:
       - name: http
         port: 3001
      publicPort: http
      environmentConfig:
        - environment: dev
          variables:
            PORT: 3001
            NODE_ENV: "dev"
            ECHO_URL: "http://echo:3000"
          monitoring: false
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
            limits:
              memory: "54Mi"
              cpu: "20m"
          replicas: 1
